version: "3.7"
services:
    alliance_admin_bot:
        build:
            context: .
            dockerfile: bot_admin.Dockerfile
        image: leelingzhen/telegram-admin-attendance-bot
        container_name: alliance_admin_bot
        volumes:
            - .secrets:/alliance_bot/.secrets
    alliance_training_bot:
        build:
            context: .
            dockerfile: bot_trainin.Dockerfile
        image: leelingzhen/telegram-attendance-bot
        container_name: alliance_training_bot
        volumes:
            - .secrets:/alliance_bot/.secrets
